version: 0.2  

phases:
  pre_build:
    commands:
      - echo PreBuild Started ...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 274201610284.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - docker login -u="ritikaj16" -p="Kalpana@1"
      - mvn clean package
      - echo Building the docker image
      - docker build -t checklist .
      - docker tag checklist:latest 274201610284.dkr.ecr.us-east-1.amazonaws.com/checklist:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 274201610284.dkr.ecr.us-east-1.amazonaws.com/checklist:latest
      - echo Writing definition files
      - printf '[{"name":"checklist","imageUri":"%s"}]' 274201610284.dkr.ecr.us-east-1.amazonaws.com/checklist:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
